# Generated by Django 6.0.1 on 2026-04-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otprecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='SavedAddress',
        ),
    ]
