# Generated by Django 6.0.1 on 2026-04-26 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('target_role', models.CharField(choices=[('customer', 'Customer'), ('technician', 'Technician')], max_length=16)),
                ('payload', models.JSONField()),
                ('is_critical', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_eventlog',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='evlog_user_created_idx'), models.Index(fields=['user', 'is_critical', 'acknowledged_at'], name='evlog_user_crit_ack_idx')],
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text='FCM registration token (globally unique across devices).', max_length=500, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], help_text='Platform — drives per-platform FCM payload shape.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='False when FCM returned UNREGISTERED/INVALID_ARGUMENT. Do not delete — keep for audit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this device token.', on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM Device',
                'verbose_name_plural': 'FCM Devices',
                'db_table': 'fcm_devices_fcmdevice',
                'indexes': [models.Index(fields=['user', 'is_active'], name='fcm_devices_user_id_f70e36_idx')],
            },
        ),
    ]
