# Generated by Django 6.0.1 on 2026-04-23 15:04

import django.db.models.deletion
from django.db import migrations, models


def clear_orphaned_address_ids(apps, schema_editor):
    # address_id values still point to the old customers_savedaddress table rows which
    # were wiped by the previous migration. NULL them out so MySQL's FK constraint
    # doesn't block the AlterField below.
    JobBooking = apps.get_model('bookings', 'JobBooking')
    JobBooking.objects.update(address=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_address_price_fields'),
        ('customers', '0002_customeraddress'),
    ]

    operations = [
        migrations.RunPython(clear_orphaned_address_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='jobbooking',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='customers.customeraddress'),
        ),
    ]
