# Generated by Django 6.0.1 on 2026-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbooking',
            name='accepted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
