# Generated by Django 6.0.1 on 2026-05-08 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_drop_accepted_at_add_awaiting_status'),
        ('catalog', '0007_add_duration_minutes'),
        ('technicians', '0007_collapse_skill_rate_to_labor_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbooking',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='actual_address_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='base_services_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='cash_collected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='cash_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='cash_collection_method',
            field=models.CharField(default='cash', max_length=16),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='discount_applied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='dispute_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='en_route_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='final_cash_to_collect',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='inspection_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='inspection_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='no_show_actor',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='no_show_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_bookings', to='bookings.jobbooking'),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='promo_code_snapshot',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='promo_discount_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='quote_first_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobbooking',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'Awaiting tech accept'), ('CONFIRMED', 'Confirmed'), ('EN_ROUTE', 'En route'), ('ARRIVED', 'Arrived'), ('INSPECTING', 'Inspecting'), ('QUOTED', 'Quoted'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('COMPLETED_INSPECTION_ONLY', 'Completed (inspection only)'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('NO_SHOW', 'No show'), ('DISPUTED', 'Disputed'), ('PENDING', 'Pending (legacy, do not use for new bookings)')], default='AWAITING', max_length=32),
        ),
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After'), ('QUOTE', 'Quote evidence'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('image', models.ImageField(upload_to='booking_attachments/')),
                ('caption', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bookings.jobbooking')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booking_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('SUPERSEDED', 'Superseded (replaced by next revision)')], default='DRAFT', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_upsell', models.BooleanField(default=False)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='bookings.jobbooking')),
            ],
            options={
                'ordering': ['booking_id', 'revision_number'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.jobbooking')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.subservice')),
                ('sourced_quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshotted_into_items', to='bookings.quote')),
            ],
            options={
                'ordering': ['booking_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('priced_at', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bookings.quote')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.subservice')),
            ],
            options={
                'ordering': ['quote_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_intake_method', models.CharField(choices=[('FORM', 'Form'), ('CHATBOT', 'Chatbot')], default='FORM', max_length=16)),
                ('initial_reason', models.TextField()),
                ('chat_log', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('resolution_outcome', models.CharField(choices=[('NONE', 'None'), ('REFUND_CUSTOMER', 'Refund customer'), ('PENALIZE_TECH', 'Penalize tech'), ('DISMISS', 'Dismiss')], default='NONE', max_length=32)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.jobbooking')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TechReliabilityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('TECH_CANCEL', 'Tech cancelled job'), ('TECH_NO_SHOW', 'Tech reported as no-show by customer')], max_length=32)),
                ('phase', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_reliability_incidents', to='bookings.jobbooking')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_incidents', to='technicians.technicianprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dispute_evidence/')),
                ('caption', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='bookings.supportticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ticket_id', 'uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('booking', 'revision_number'), name='unique_quote_revision_per_booking'),
        ),
        migrations.AddIndex(
            model_name='techreliabilityincident',
            index=models.Index(fields=['technician', '-created_at'], name='bookings_te_technic_cf84d3_idx'),
        ),
    ]
