# Generated by Django 6.0.1 on 2026-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_supportticket_resolved_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUBMITTED')), fields=('booking', 'is_upsell'), name='unique_submitted_quote_per_booking_flavour'),
        ),
    ]
