# Generated by Django 6.0.1 on 2026-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_quote_unique_submitted_quote_per_booking_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbooking',
            name='customer_acknowledged_arrival_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
