# Generated by Django 6.0.1 on 2026-03-03 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (Rs.)')], default='FIXED', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funded_by', models.CharField(choices=[('PLATFORM', 'Platform-Funded'), ('TECHNICIAN', 'Technician-Funded')], default='PLATFORM', max_length=20)),
                ('image', models.ImageField(upload_to='promo_banners/')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured_on_home', models.BooleanField(default=True)),
                ('target_subservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.subservice')),
            ],
        ),
    ]
