# Generated by Django 6.0.1 on 2026-03-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_base_inspection_fee'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='target_subservice',
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='target_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.service'),
        ),
    ]
