"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os  # ADD THIS IMPORT
import sys
import environ
from pathlib import Path

# 1. Initialize BASE_DIR once
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Initialize environ
env = environ.Env(DEBUG=(bool, False))

# 3. Read the .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# 4. Use env variables
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

# Twilio — live credentials (DEBUG=False / production)
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN')
TWILIO_FROM_NUMBER = env('TWILIO_FROM_NUMBER')

# Twilio — test credentials (DEBUG=True / development, no real SMS sent)
TWILIO_TEST_ACCOUNT_SID = env('TWILIO_TEST_ACCOUNT_SID')
TWILIO_TEST_AUTH_TOKEN = env('TWILIO_TEST_AUTH_TOKEN')
TWILIO_TEST_FROM_NUMBER = env('TWILIO_TEST_FROM_NUMBER', default='+15005550006')

# --- Firebase (FCM) ---------------------------------------------------------
# Actual SDK initialization happens lazily in ``core.firebase.init_firebase()``
# to avoid side effects on every settings import (tests, management commands).
FIREBASE_CREDENTIALS_PATH = env(
    'FIREBASE_CREDENTIALS_PATH',
    default=os.path.join(BASE_DIR, 'firebase_credintials.json'),
)

# --- Redis / Channels / Celery ---------------------------------------------
# Channels uses Redis DB 0; Celery broker uses DB 1 — keep them isolated so a
# queue backlog can never stall WebSocket group fan-out (or vice versa).
REDIS_HOST = env('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = env.int('REDIS_PORT', default=6379)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"redis://{REDIS_HOST}:{REDIS_PORT}/0"],
        },
    },
}

CELERY_BROKER_URL = env(
    'CELERY_BROKER_URL', default=f'redis://{REDIS_HOST}:{REDIS_PORT}/1'
)
CELERY_RESULT_BACKEND = env(
    'CELERY_RESULT_BACKEND', default=f'redis://{REDIS_HOST}:{REDIS_PORT}/1'
)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
# Transient broker outages must never crash the caller of broadcast_event —
# dispatch wraps .delay() in its own try/except, but we also disable implicit
# retries on publish so the web worker returns fast.
CELERY_TASK_PUBLISH_RETRY = False

# --- Booking orchestrator ---------------------------------------------------
# Lenient (False, default): the manual `arrived` endpoint logs a warning when
# the tech's claimed coords are >100m from the customer's address but still
# allows the transition. Strict (True): the same mismatch returns
# 400 not_at_customer_location. The auto path (auto_transition.evaluate_on_location)
# is unaffected — it never auto-flips on a mismatch regardless of this flag.
BOOKING_GEOFENCE_STRICT = env.bool('BOOKING_GEOFENCE_STRICT', default=False)


# --- Wallet / payment finance --------------------------------------------
# Which FinancePort adapter the booking orchestrator gets via
# ``bookings.adapters.get_default_finance_service``. 'wallet' = real
# ledger writes (WalletFinanceAdapter). 'null' = no-op (NullFinanceAdapter,
# for tests that exercise the orchestrator without finance side-effects).
FINANCE_BACKEND = env('FINANCE_BACKEND', default='wallet')

# Registry of PaymentGatewayPort adapters. Add EasyPaisa / real JazzCash
# entries here; ``wallet.services.gateway_factory.get_gateway`` does the
# lazy import. The mock adapter is the dev default — Thursday adds the
# real 'jazzcash' entry when the JazzCash SDK lands.
PAYMENT_GATEWAYS = {
    'mock': 'wallet.adapters.mock_jazzcash_gateway.MockJazzCashGateway',
}
DEFAULT_PAYMENT_GATEWAY = env('DEFAULT_PAYMENT_GATEWAY', default='mock')


# Application definition

INSTALLED_APPS = [
    # Daphne MUST be the first entry so its `runserver` command replaces
    # Django's default WSGI runserver. Channels 4.x removed its own runserver
    # patch — without `daphne` here, `python manage.py runserver` falls back
    # to plain WSGI and every WebSocket handshake (`/ws/events/`) returns
    # HTTP 404 silently. The `daphne <module>` CLI continues to work either
    # way; this entry just keeps the dev workflow uniform.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    # third party apps
    'rest_framework',
    'rest_framework.authtoken',  # 1. ADD THIS for Token support
    'channels',
    #apps
    'accounts',
    'technicians',
    'catalog',
    'marketing',
    'customers',
    'bookings',
    'wallet',
    'django_extensions',
    # Central Event Dispatch Hub
    'core.apps.CoreConfig',
    'realtime.apps.RealtimeConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # The correct class name
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic output for production



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # For now, let's allow all users to access endpoints unless we specifically block them
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'EXCEPTION_HANDLER': 'core.common.failures.exception.custom_exception_handler',
}
CORS_ALLOW_ALL_ORIGINS = True




# settings.py

# ... existing code (MIDDLEWARE, TEMPLATES, DATABASES, etc.) ...

import sys

# Override database for tests to use in-memory SQLite for speed and isolation
if 'test' in sys.argv or 'test_coverage' in sys.argv or 'pytest' in sys.modules:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
    
    # Use a faster password hasher to speed up test execution
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')