# Generated by Django 6.0.1 on 2026-03-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_subservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_inspection_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6),
        ),
    ]
