# Generated by Django 6.0.1 on 2026-04-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_base_inspection_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='image',
        ),
        migrations.AddField(
            model_name='subservice',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
