# Generated by Django 6.0.1 on 2026-04-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_replace_subservice_image_with_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='card_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
