# Generated by Django 6.0.1 on 2026-04-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_card_image_url_to_subservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
