# Generated by Django 6.0.1 on 2026-04-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_icon_url_to_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='subservice',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
