# Generated by Django 6.0.1 on 2026-05-12 17:12

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='base_inspection_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6, validators=[catalog.models._validate_whole_rupee]),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[catalog.models._validate_whole_rupee]),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[catalog.models._validate_whole_rupee]),
        ),
    ]
