# Generated by Django 6.0.1 on 2026-05-15 20:36

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_service_base_inspection_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='base_inspection_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Whole rupees only — no paisa. E.g. 500, not 500.50.', max_digits=6, validators=[catalog.models._validate_whole_rupee]),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Typical job length in minutes for an inspection in this category. Drives availability slot length when no specific sub-service is chosen. E.g. AC service: 60–90.'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Whole rupees only — no paisa. For fixed-price gigs this is the locked price; for labor gigs it is the lower bound of the technician's rate band.", max_digits=10, validators=[catalog.models._validate_whole_rupee]),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Estimated job length in minutes for this specific gig. Leave blank to inherit from the parent service's default_duration_minutes. E.g. AC coil clean: 90.", null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Whole rupees only. Used ONLY when ``is_fixed_price`` is False — upper bound of the technician's labor rate band. Leave blank for fixed-price gigs.", max_digits=10, null=True, validators=[catalog.models._validate_whole_rupee]),
        ),
    ]
