# Generated by Django 6.0.1 on 2026-05-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0011_jobbooking_customer_acknowledged_arrival_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=64)),
                ('account_title', models.CharField(max_length=128)),
                ('iban', models.CharField(max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_intent', to='bookings.supportticket')),
            ],
        ),
    ]
