# Generated by Django 6.0.1 on 2026-05-12 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0011_jobbooking_customer_acknowledged_arrival_at'),
        ('technicians', '0007_collapse_skill_rate_to_labor_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=128)),
                ('account_title', models.CharField(max_length=128)),
                ('account_number_or_iban', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='technicians.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianJazzCashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(help_text='Pakistan MSISDN. Format normalisation belongs at the serializer, not the model.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jazzcash_accounts', to='technicians.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed. Positive = credit (tech earns), negative = debit.', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('COMMISSION_DEBIT', 'Commission debit'), ('TOPUP_CREDIT', 'Top-up credit'), ('WITHDRAWAL_DEBIT', 'Withdrawal debit'), ('REFUND_DEBIT', 'Refund debit'), ('ADJUSTMENT', 'Manual adjustment')], max_length=40)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='TechnicianProfile.current_wallet_balance snapshot AFTER this row was applied.', max_digits=10)),
                ('gateway_reference', models.CharField(blank=True, default='', help_text='Opaque gateway transaction id (e.g. JazzCash ppmpf-xxx). Empty for non-gateway rows.', max_length=128)),
                ('transaction_reference_number', models.CharField(blank=True, default='', help_text='Internal idempotency key. Empty allowed; uniqueness enforced via partial index.', max_length=128)),
                ('is_manual_adjustment', models.BooleanField(default=False, help_text='True for admin-initiated ADJUSTMENT rows. Default False for system-written entries.')),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='technicians.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_attempted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_name', models.CharField(help_text='Registry key in settings.PAYMENT_GATEWAYS (e.g. "jazzcash", "mock").', max_length=32)),
                ('gateway_status', models.CharField(choices=[('PENDING', 'Pending'), ('REDIRECTED', 'Redirected to gateway'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=20)),
                ('gateway_session_id', models.CharField(blank=True, default='', max_length=128)),
                ('gateway_redirect_url', models.URLField(blank=True, default='')),
                ('gateway_callback_payload', models.JSONField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_topups', to='technicians.technicianprofile')),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topup', to='wallet.wallettransaction')),
            ],
        ),
        migrations.CreateModel(
            name='RefundDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_reason', models.CharField(max_length=255)),
                ('wallet_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_deduction', to='wallet.wallettransaction')),
            ],
        ),
        migrations.CreateModel(
            name='JobCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_amount', models.DecimalField(decimal_places=2, help_text='Tech-facing revenue this booking. Commission_amount = payout_amount * commission_rate.', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Snapshot of PLATFORM_COMMISSION_RATE at the moment of recording. Decoupled from globals.', max_digits=4)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_note', models.CharField(blank=True, default='', max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='bookings.jobbooking')),
                ('wallet_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job_commission', to='wallet.wallettransaction')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved (queued for processing)'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed (paid out)')], default='PENDING_REVIEW', max_length=20)),
                ('admin_external_ref', models.CharField(blank=True, default='', help_text='Admin-entered reference from the out-of-band payout (JazzCash merchant txn id, bank wire ref, etc.).', max_length=128)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('payout_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallet.technicianbankaccount')),
                ('payout_jazzcash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallet.technicianjazzcashaccount')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='technicians.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalFulfilment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_note', models.TextField(blank=True, default='')),
                ('fulfilled_at', models.DateTimeField(auto_now_add=True)),
                ('wallet_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_fulfilment', to='wallet.wallettransaction')),
                ('withdrawal_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fulfilment', to='wallet.withdrawalrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='technicianbankaccount',
            index=models.Index(fields=['technician', 'is_active'], name='wallet_tech_technic_bfac8f_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianjazzcashaccount',
            index=models.Index(fields=['technician', 'is_active'], name='wallet_tech_technic_b84d82_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['technician', '-timestamp'], name='wallet_wall_technic_a17b43_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_reference_number', ''), _negated=True), fields=('transaction_reference_number',), name='wallet_walletxn_unique_txn_ref'),
        ),
        migrations.AddIndex(
            model_name='wallettopup',
            index=models.Index(fields=['technician', '-initiated_at'], name='wallet_wall_technic_7dd075_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettopup',
            index=models.Index(fields=['gateway_status'], name='wallet_wall_gateway_4717f3_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['technician', '-requested_at'], name='wallet_with_technic_424445_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status'], name='wallet_with_status_f692e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payout_bank_account__isnull', False), ('payout_jazzcash_account__isnull', True)), models.Q(('payout_bank_account__isnull', True), ('payout_jazzcash_account__isnull', False)), _connector='OR'), name='wallet_withdrawalrequest_exactly_one_payout_account'),
        ),
    ]
