# Generated by Django 6.0.1 on 2026-05-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettopup',
            name='gateway_request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
