// lib/features/customer/home/domain/entities/home_feed_entity.dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'home_feed_entity.freezed.dart';

/// Contract: Fed by GET /api/customers/home/
/// Represents a high-level category in the Discovery grid.
/// `iconName` maps to a Flutter SVG asset via `IconAssets.path()`.
@freezed
abstract class CategoryEntity with _$CategoryEntity {
  const factory CategoryEntity({
    required int id,
    required String name,
    required String iconName,
  }) = _CategoryEntity;
}

/// Contract: Fed by GET /api/customers/home/
/// Represents an active promotional banner with Dumb UI text fields.
@freezed
abstract class PromotionEntity with _$PromotionEntity {
  const factory PromotionEntity({
    required int id,
    required String title,
    required String bannerImageUrl,
    required String promoDescription, // Dumb UI String generated by backend
    required String buttonText,       // Dumb UI String generated by backend
  }) = _PromotionEntity;
}

/// Contract: Fed by GET /api/customers/home/
/// Represents a "Featured Instant Book" fixed-price sub-service.
@freezed
abstract class FixedGigEntity with _$FixedGigEntity {
  const factory FixedGigEntity({
    required int id,
    required String name,
    required String basePrice,
    required String parentCategory,
    required String imageUrl,
  }) = _FixedGigEntity;
}

/// Contract: Fed by GET /api/customers/home/
/// Represents a highly-rated technician near the user's GPS coordinates.
@freezed
abstract class TechnicianFeedEntity with _$TechnicianFeedEntity {
  const factory TechnicianFeedEntity({
    required int id,
    required String fullName,
    required String primaryCategory,
    required String city,
    required String profilePicture,
    required double ratingAverage,
    required int reviewCount,
    double? distanceKm, // Nullable: Handled gracefully by backend if GPS fails
    required double bayesianScore,
    required bool isActive,
  }) = _TechnicianFeedEntity;
}

/// Contract: Fed by GET /api/customers/home/
/// The master wrapper entity aggregating all Home Screen components.
@freezed
abstract class HomeFeedEntity with _$HomeFeedEntity {
  const factory HomeFeedEntity({
    required List<CategoryEntity> categories,
    required List<PromotionEntity> promotions,
    required List<FixedGigEntity> fixedGigs,
    required List<TechnicianFeedEntity> topTechnicians,
  }) = _HomeFeedEntity;
}
