# Generated by Django 6.0.1 on 2026-04-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_customeraddress'),
        ('customers', '0002_customeraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedAddress',
        ),
    ]
