# Generated by Django 6.0.1 on 2026-03-03 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='temp_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('LHR', 'Lahore'), ('KHI', 'Karachi'), ('ISL', 'Islamabad')], max_length=3)),
                ('cnic_number', models.CharField(max_length=15, unique=True)),
                ('cnic_front_image', models.ImageField(upload_to='tech_docs/cnic/')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(help_text='Details about qualifications and expertise.')),
                ('profile_picture', models.ImageField(upload_to='tech_profiles/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('base_latitude', models.FloatField(blank=True, null=True)),
                ('base_longitude', models.FloatField(blank=True, null=True)),
                ('max_travel_radius_km', models.IntegerField(default=10)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianServiceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_picture', models.ImageField(upload_to='tech_docs/licenses/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.service')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_licenses', to='technicians.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subservice')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicians.technicianprofile')),
            ],
            options={
                'unique_together': {('technician', 'sub_service')},
            },
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='skills',
            field=models.ManyToManyField(related_name='technicians', through='technicians.TechnicianSkill', to='catalog.subservice'),
        ),
    ]
