# Generated by Django 6.0.1 on 2026-02-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianskill',
            name='license_picture',
        ),
        migrations.CreateModel(
            name='TechnicianServiceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_picture', models.ImageField(upload_to='tech_docs/licenses/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicians.service')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_licenses', to='technicians.technicianprofile')),
            ],
        ),
    ]
