# Generated by Django 6.0.1 on 2026-03-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_technicianserviceperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianskill',
            name='base_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='technicianskill',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
