# Generated by Django 6.0.1 on 2026-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0005_add_technician_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='current_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
