# Generated by Django 6.0.1 on 2026-05-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0007_collapse_skill_rate_to_labor_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
