# Generated by Django 6.0.1 on 2026-05-15 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_service_base_inspection_fee_and_more'),
        ('technicians', '0008_add_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='technicianprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='technicianprofile_rejected_requires_reason'),
        ),
    ]
