# Generated by Django 6.0.1 on 2026-05-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_help_text_only'),
        ('technicians', '0010_technicianprofile_work_address_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianservicelicense',
            name='license_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tech_docs/licenses/'),
        ),
        migrations.AlterUniqueTogether(
            name='technicianservicelicense',
            unique_together={('technician', 'service')},
        ),
    ]
