# Generated by Django 6.0.1 on 2026-05-13 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_key', models.CharField(db_index=True, max_length=32)),
                ('context', models.JSONField(default=dict)),
                ('state', models.JSONField(default=dict)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('output_refs', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLlmCallQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_llm_quotas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('BOT', 'Bot'), ('SYSTEM', 'System')], max_length=8)),
                ('text', models.TextField(blank=True)),
                ('structured', models.JSONField(blank=True, default=dict)),
                ('phase', models.CharField(blank=True, max_length=32)),
                ('lang', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chatbot/%Y/%m/')),
                ('mime_type', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chatbot.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='chatbot.message')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'persona_key', 'is_closed'], name='chatbot_con_user_id_2a437e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['persona_key', 'created_at'], name='chatbot_con_persona_f663a5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyllmcallquota',
            index=models.Index(fields=['user', 'date'], name='chatbot_dai_user_id_b143dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyllmcallquota',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_mes_convers_b353f0_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_att_convers_79e38b_idx'),
        ),
    ]
