# Generated by Django 6.0.1 on 2026-04-24 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text='FCM registration token (globally unique across devices).', max_length=500, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], help_text='Platform — drives per-platform FCM payload shape.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='False when FCM returned UNREGISTERED/INVALID_ARGUMENT. Do not delete — keep for audit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this device token.', on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM Device',
                'verbose_name_plural': 'FCM Devices',
                'indexes': [models.Index(fields=['user', 'is_active'], name='fcm_devices_user_id_f70e36_idx')],
            },
        ),
    ]
