// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwfsNc9NA917hr-hrQJoMU14NpaIgpFiU',
    appId: '1:867664502750:web:1d24ce790783a4fcbd074f',
    messagingSenderId: '867664502750',
    projectId: 'karigar-8e3d3',
    authDomain: 'karigar-8e3d3.firebaseapp.com',
    storageBucket: 'karigar-8e3d3.firebasestorage.app',
    measurementId: 'G-HWRDW7B79H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDExUIXeb9DTYJ8Hw0i-xaXRVUELapyvNw',
    appId: '1:867664502750:android:9031b55dac98fba9bd074f',
    messagingSenderId: '867664502750',
    projectId: 'karigar-8e3d3',
    storageBucket: 'karigar-8e3d3.firebasestorage.app',
  );
}
