# Generated by Django 6.0.1 on 2026-04-24 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('target_role', models.CharField(choices=[('customer', 'Customer'), ('technician', 'Technician')], max_length=16)),
                ('payload', models.JSONField()),
                ('is_critical', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='evlog_user_created_idx'), models.Index(fields=['user', 'is_critical', 'acknowledged_at'], name='evlog_user_crit_ack_idx')],
            },
        ),
    ]
